config/routes.rb
Rails.application.routes.draw do
  get 'publishers/new'
  get 'publishers/create'
  get 'publishers/update'
  get 'publishers/edit'
  get 'publishers/destroy'
  get 'publishers/index'
  get 'publishers/show'
  get 'authors/new'
  get 'authors/create'
  get 'authors/update'
  get 'authors/edit'
  get 'authors/destroy'
  get 'authors/index'
  get 'authors/show'
  get 'categories/new'
  get 'categories/create'
  get 'categories/update'
  get 'categories/edit'
  get 'categories/destroy'
  get 'categories/index'
  get 'categories/show'
  get 'books/new'
  get 'books/create'
  get 'books/update'
  get 'books/edit'
  get 'books/destroy'
  get 'books/index'
  get 'books/show'
  get 'about/index'
  get 'about' => 'about#index'

  root 'books#index'


  resources :books
  resources :authors
  resources :categories
  resources :publishers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :books

    validates :first_name, presence: true
    validates :last_name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :category
    belongs_to :author
    belongs_to :publisher
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books

    validates :name, presence: true,
                length: {minimum:3}
end

app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :books

    validates :name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = "About Us";
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = 'Add new Author'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:notice] = "Author Created"

      redirect_to authors_path
    else
      render 'new'
    end
  end

  def update
    @author = Author.find(params[:id])
    
    @author.update(author_params)

    flash[:notice] = 'Author Updated'

    redirect_to authors_path
  end

  def edit
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])
    
    @author.destroy

    flash[:notice] = 'Author Removed'
    redirect_to authors_path
  end

  def index
    @authors = Author.all
  end

  private 
    def  author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = 'Add Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new
  end

  def create
    @book = Book.new(book_params)
    @book.save

    flash[:notice] = 'Book Added'
    redirect_to books_path
   
  end

  def update
    @book = Book.find(params[:id])
    
    @book.update(book_params)

    flash[:notice] = 'Book Updated'

    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
     @book = Book.find(params[:id])
    
    @book.destroy

    flash[:notice] = 'Book Removed'
    redirect_to books_path
  end

  def index
    @books = Book.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @categories = Category.all
  end

  private 
    def  book_params
      params.require(:book).permit(:title, :category_id, :author_id, :publisher_id, :isbn, :price, :buy, :format, :excerpt, :pages, :year, :coverpath)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Add new Category'
    @category = Category.new
  end

  def create
    @category = Category.new(catergory_params)
    
    if @category.save
      flash[:notice] = "Category Created"

      redirect_to categories_path
    else
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])
    
    @category.update(catergory_params)

    flash[:notice] = 'Category Updated'

    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    
    @category.destroy

    flash[:notice] = 'Category Removed'
    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @books = @category.books
  end
  private 
    def  catergory_params
      params.require(:category).permit(:name)
    end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = 'Add new Publisher'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:notice] = "Publisher Created"

      redirect_to publishers_path
    else
      render 'new'
    end
  end

  def update
    @publisher = Publisher.find(params[:id])
    
    @publisher.update(publisher_params)

    flash[:notice] = 'Publisher Updated'

    redirect_to publishers_path
  end
  def edit
    @publisher = Publisher.find(params[:id])
  end

  def destroy
    @publisher = Publisher.find(params[:id])
    
    @publisher.destroy

    flash[:notice] = 'Publisher Removed'
    redirect_to publishers_path
  end

  def index
    @publishers = Publisher.all
  end


  private 
    def  publisher_params
      params.require(:publisher).permit(:name)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>Lorem Ipsum is simply dummy text of the printing and 
typesetting industry. Lorem Ipsum has been the industry's 
standard dummy text ever since the 1500s, when an unknown 
printer took a galley of type and scrambled it to make a type 
specimen book. It has survived not only five centuries, but 
also the leap into electronic typesetting, remaining essentially
unchanged. It was popularised in the 1960s with the release of  
Letraset sheets containing Lorem Ipsum passages, and more 
recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h2> Edit Author</h2>
<%= form_for @author do |x| %>

    <%# Check for errors %>
    <% if @author.errors.any? %>

        <%# Display error messages %>
        <%  @author.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg%></div>
        <% end %>
    <% end %>
    <div class="form-group">
        <%= x.label :first_name%> <br/>
        <%= x.text_field :first_name, class: 'form-control'%><br />
    </div>

    <div class="form-group">
        <%= x.label :last_name%> <br/>
        <%= x.text_field :last_name, class: 'form-control'%><br />
    </div>

    <%= x.submit "submit", class:'btn btn-primary' %>
    <%= link_to "cancel", authors_path, class:'btn btn-default'%>
<% end %>

app/views/authors/index.html.erb
<h2>Authors</h2>

<table class="table table-striped">
    <tr>
        <th>Author Name</th>
        <th>Actions</th>
    </tr>

    <% @authors.each do |author| %>
        <tr>
            <td><%= author.first_name %> <%= author.last_name %></td>
            <td><%= link_to 'Edit', edit_author_path(author.id)%> |
            <%= link_to 'Delete', author_path(author), method: :delete,
            data: {confirm: 'Are you sure?'}%></td>
        
        </tr>
    <% end %>
</table>

app/views/authors/new.html.erb
<h2> Add New Author</h2>
<%= form_for @author do |x| %>

    <%# Check for errors %>
    <% if @author.errors.any? %>

        <%# Display error messages %>
        <%  @author.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg%></div>
        <% end %>
    <% end %>
    <div class="form-group">
        <%= x.label :first_name%> <br/>
        <%= x.text_field :first_name, class: 'form-control'%><br />
    </div>

    <div class="form-group">
        <%= x.label :last_name%> <br/>
        <%= x.text_field :last_name, class: 'form-control'%><br />
    </div>

    <%= x.submit "submit", class:'btn btn-primary' %>
    <%= link_to "cancel", authors_path, class:'btn btn-default'%>
<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h2> Edit Book </h2>

<%= form_for @book do |x| %>
    <div class="form-group">
        <%= x.label :title%> <br/>
        <%= x.text_field :title, class: 'form-control'%><br />
    </div>

    <div class="form-group">
        <%= x.label :isbn%> <br/>
        <%= x.text_field :isbn, class: 'form-control'%><br />
    </div>

    <div class="form-group">
        <%= x.label :category %> <br/>
        <%= x.select :category_id, Category.all.collect { |y| [y.name, y.id]},
        {:include_blank => 'select one'}, class: 'form-control'%><br /><br />
    </div>

     <div class="form-group">
        <%= x.label :author %> <br/>
        <%= x.select :author_id, Author.all.collect { |y| [y.first_name + ' ' + y.last_name, y.id]},
        {:include_blank => 'select one'}, class: 'form-control'%><br /><br />
    </div>

     <div class="form-group">
        <%= x.label :publisher %> <br/>
        <%= x.select :publisher_id, Publisher.all.collect { |y| [y.name, y.id]},
        {:include_blank => 'select one'}, class: 'form-control'%><br /><br />
    </div>

    <div class="form-group">
        <%= x.label :excerpt%> <br/>
        <%= x.text_area :excerpt, class: 'form-control'%><br />
    </div>
  
    <div class="form-group">
        <%= x.label :pages%> <br/>
        <%= x.number_field :pages, class: 'form-control'%><br />
    </div>
    <div class="form-group">
        <%= x.label :price%> <br/>
        <%= x.text_field :price, class: 'form-control'%><br />
    </div>

    <div class="form-group">
        <%= x.label :buy%> <br/>
        <%= x.text_field :buy, class: 'form-control'%><br />
    </div>
    <div class="form-group">
        <%= x.label :format%> <br/>
        <%= x.text_field :format, class: 'form-control'%><br />
    </div>

     <div class="form-group">
        <%= x.label :year%> <br/>
        <%= x.text_field :year, class: 'form-control'%><br />
    </div>

     <div class="form-group">
        <%= x.label :coverpath%> <br/>
        <%= x.text_field :coverpath, class: 'form-control'%><br />
    </div>

    <%= x.submit "submit", class:'btn btn-primary' %>
    <%= link_to "cancel", books_path, class:'btn btn-default'%>
<% end %>

app/views/books/index.html.erb
<div id="books-index">
    <% @books.each_slice(4) do |book|%>
        <div class="row">
            <% book.each do |book| %>
                <div class="col-md-3 col-sm-3">
                    <h5><%= book.title%> </h5>
                    <% if book.coverpath %>                   
                        <%= image_tag(book.coverpath)%>
                    <% end %>
                    <%= link_to 'Read More', book_path(book), class:'btn btn-primary'%>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/books/new.html.erb
<h2> Add New Book </h2>

<%= form_for @book do |x| %>
    <div class="form-group">
        <%= x.label :title%> <br/>
        <%= x.text_field :title, class: 'form-control'%><br />
    </div>

    <div class="form-group">
        <%= x.label :isbn%> <br/>
        <%= x.text_field :isbn, class: 'form-control'%><br />
    </div>

    <div class="form-group">
        <%= x.label :category %> <br/>
        <%= x.select :category_id, Category.all.collect { |y| [y.name, y.id]},
        {:include_blank => 'select one'}, class: 'form-control'%><br /><br />
    </div>

     <div class="form-group">
        <%= x.label :author %> <br/>
        <%= x.select :author_id, Author.all.collect { |y| [y.first_name + ' ' + y.last_name, y.id]},
        {:include_blank => 'select one'}, class: 'form-control'%><br /><br />
    </div>

     <div class="form-group">
        <%= x.label :publisher %> <br/>
        <%= x.select :publisher_id, Publisher.all.collect { |y| [y.name, y.id]},
        {:include_blank => 'select one'}, class: 'form-control'%><br /><br />
    </div>

    <div class="form-group">
        <%= x.label :excerpt%> <br/>
        <%= x.text_area :excerpt, class: 'form-control'%><br />
    </div>
  
    <div class="form-group">
        <%= x.label :pages%> <br/>
        <%= x.number_field :pages, class: 'form-control'%><br />
    </div>
    <div class="form-group">
        <%= x.label :price%> <br/>
        <%= x.text_field :price, class: 'form-control'%><br />
    </div>

    <div class="form-group">
        <%= x.label :buy%> <br/>
        <%= x.text_field :buy, class: 'form-control'%><br />
    </div>
    <div class="form-group">
        <%= x.label :format%> <br/>
        <%= x.text_field :format, class: 'form-control'%><br />
    </div>

     <div class="form-group">
        <%= x.label :year%> <br/>
        <%= x.text_field :year, class: 'form-control'%><br />
    </div>

     <div class="form-group">
        <%= x.label :coverpath%> <br/>
        <%= x.text_field :coverpath, class: 'form-control'%><br />
    </div>

    <%= x.submit "submit", class:'btn btn-primary' %>
    <%= link_to "cancel", books_path, class:'btn btn-default'%>
<% end %>

app/views/books/show.html.erb
<div id="books-show">
    <h2> <%= @book.title %></h2>
    <div class="books-show-left">
        <%= image_tag(@book.coverpath)%>
    </div>
    <div class="books-show-right">
        <h3>Book Info:</h3>
        <ul>
            <li><strong>Category: </strong> <%= @book.category.name%></li>
            <li><strong>Author: </strong> <%= @book.author.first_name%> 
                <%= @book.author.last_name%></li>
            <li><strong>Publisher: </strong> <%= @book.publisher.name%></li>
            <li><strong>Year: </strong> <%= @book.year%></li>
            <li><strong> ISBN: </strong> <%= @book.isbn%></li>
            <li><strong>Format: </strong> <%= @book.format%></li>
            <li><strong>Pages: </strong> <%= @book.pages%></li>
        </ul>
        <%= link_to "Buy For "+@book.price, @book.buy, 
        class: 'btn btn-success', target: '_blank'%>
    </div>
    <div class="clearfix"></div>
    <h4>Excerpt</h4>
    <p><%= @book.excerpt%></p>

    <h3> Admin Functions</h3>
    <%= link_to 'Edit', edit_book_path(@book.id)%> | <%= link_to 'Delete', book_path(@book), method: :delete, data: {confirm: 'Are you sure?'} %>
</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h2> Edit Category</h2>
<%= form_for @category do |x| %>

    <%# Check for errors %>
    <% if @category.errors.any? %>
        <%  @category.errors.full_messages.each do |msg| %>

            <%# display error messages %>
            <div class="alert alert-danger"><%= msg%></div>
        <% end %>
    <% end %>
    <div class="form-group">
        <%= x.label :name%> <br/>
        <%= x.text_field :name, class: 'form-control'%><br />
    </div>

    <%= x.submit "submit", class:'btn btn-primary' %>
    <%= link_to "cancel", categories_path, class:'btn btn-default'%>
<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>

<table class="table table-striped">
    <tr>
        <th>Category Names</th>
        <th>Actions</th>
    </tr>

    <% @categories.each do |category| %>
        <tr>
            <td><%= category.name %></td>
            <td><%= link_to 'Edit', edit_category_path(category.id)%> |
            <%= link_to 'Delete', category_path(category), method: :delete,
            data: {confirm: 'Are you sure?'}%></td>
        
        </tr>
    <% end %>
</table>

app/views/categories/new.html.erb
<h2> Add New Category</h2>
<%= form_for @category do |x| %>

    <%# Check for errors %>
    <% if @category.errors.any? %>
        <%  @category.errors.full_messages.each do |msg| %>

            <%# display error messages %>
            <div class="alert alert-danger"><%= msg%></div>
        <% end %>
    <% end %>
    <div class="form-group">
        <%= x.label :name%> <br/>
        <%= x.text_field :name, class: 'form-control'%><br />
    </div>

    <%= x.submit "submit", class:'btn btn-primary' %>
    <%= link_to "cancel", categories_path, class:'btn btn-default'%>
<% end %>

app/views/categories/show.html.erb
<h2><%= @category.name%>

<div id="books-index">
    <% @books.each_slice(4) do |book|%>
        <div class="row">
            <% book.each do |book| %>
                <div class="col-md-3 col-sm-3">
                    <h5><%= book.title%> </h5>
                    <% if book.coverpath %>                   
                        <%= image_tag(book.coverpath)%>
                    <% end %>
                    <%= link_to 'Read More', book_path(book), class:'btn btn-primary'%>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= @page_title ? @page_title : 'Welcome'%> | The Bookstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-default bg-light fixed-top">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      </button>
      <div class="collapse navbar-collapse container" >
        <ul class="nav navbar-nav mr-auto">
          <li class="<%= params[:controller] == 'books' ? 'active' : '' %> pr-3"><%= link_to 'Home', root_path%></li>
          <li class="<%= params[:controller] == 'about' ? 'active' : '' %>"><%= link_to 'About', about_path%></li>
        </ul> 
        <ul class="nav navbar-nav navbar-right">
        <li class="show dropdown">
          <a class="dropdown-toggle " href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Add New <span class="caret"></span>
          </a>
          <ul class="dropdown-menu navbar-right mt-2" role="menu">
            <li><%= link_to "Book", new_book_path%></li>
            <li><%= link_to "Category", new_category_path%></li>
            <li><%= link_to "Author", new_author_path%></li>
            <li><%= link_to "Publisher", new_publisher_path%></li>
          </ul>  
        </li> 

        <li class="show dropdown">
          <a class="dropdown-toggle pl-3" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Manage<span class="caret"></span>
          </a>
          <ul class="dropdown-menu navbar-right mt-2" role="menu">
            <li><%= link_to "Category", categories_path%></li>
            <li><%= link_to "Author", authors_path%></li>
            <li><%= link_to "Publisher", publishers_path%></li>
          </ul>  
        </li> 
        </ul>
      </div>
    </nav>
    <header>
      <div class="container">
        <h1> The BookStore <small> <%= @page_title ? @page_title : 'Welcome'%></small></h1>
      </div>
    </header>

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <% if flash[:notice] %>
              <div class="alert alert-success"><%= flash[:notice]%></div>
            <% end %>
             
            <% if flash[:alert] %>
              <div class="alert alert-danger"><%= flash[:alert]%></div>
            <% end %>
             <%= yield %>
          </div>
          <div class="col-md-4">
            <%= render 'partials/sidebar'%>
          </div>
        </div>
      </div>
    </section>

    <footer>
      <div class="container">
        <p> Copyright &copy; 2019, All Right Reserved. </p>
      </div>
    </footer>
   
  </body>
</html>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about'%>
    <div class="well">
        <h3> Location Info</h3>
        <ul>
            <li> The BookStore</li>
            <li> 499 Massachusetts Av, Unit 2</li>
            <li> Boston, MA 02110</li>
            <li> Phone: (617) 555-5555</li>
            <li> Email: support@thebookstore.com</li>
        </ul>
    </div>
<% end%>
<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show'%>
    <div class="list-group">
        <% @categories.each do |category| %>
            <%= link_to category.name, category_path(category.id),  class:'list-group-item' %>
        <% end %>
    </div>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h2> Edit Publisher</h2>
<%= form_for @publisher do |x| %>

    <% if @publisher.errors.any? %>
        <%# Check for errors %>
        <%  @publisher.errors.full_messages.each do |msg| %>
            <%# Display error messages %>
            <div class="alert alert-danger"><%= msg%></div>
        <% end %>
    <% end %>
    <div class="form-group">
        <%= x.label :name%> <br/>
        <%= x.text_field :name, class: 'form-control'%><br />
    </div>
    <%= x.submit "submit", class:'btn btn-primary' %>
    <%= link_to "cancel", publishers_path, class:'btn btn-default'%>
<% end %>

app/views/publishers/index.html.erb
<h2>Publishers</h2>

<table class="table table-striped">
    <tr>
        <th>Publisher Names</th>
        <th>Actions</th>
    </tr>

    <% @publishers.each do |publisher| %>
        <tr>
            <td><%= publisher.name %></td>
            <td><%= link_to 'Edit', edit_publisher_path(publisher.id)%> |
            <%= link_to 'Delete', publisher_path(publisher), method: :delete,
            data: {confirm: 'Are you sure?'}%></td>
        
        </tr>
    <% end %>
</table>

app/views/publishers/new.html.erb
<h2> Add New Publisher</h2>
<%= form_for @publisher do |x| %>

    <% if @publisher.errors.any? %>
        <%# Check for errors %>
        <%  @publisher.errors.full_messages.each do |msg| %>
            <%# Display error messages %>
            <div class="alert alert-danger"><%= msg%></div>
        <% end %>
    <% end %>
    <div class="form-group">
        <%= x.label :name%> <br/>
        <%= x.text_field :name, class: 'form-control'%><br />
    </div>
    <%= x.submit "submit", class:'btn btn-primary' %>
    <%= link_to "cancel", publishers_path, class:'btn btn-default'%>
<% end %>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>